apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aks-app
  template:
    metadata:
      labels:
        app: aks-app
    spec:
      containers:
      - name: aks-app
        image: myacr1234.azurecr.io/aks-app:latest
        ports:
        - containerPort: 3000